name: PrintSourcesDirectory

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    Write-Host "Build.SourcesDirectory: $env:Build_SourcesDirectory"
  displayName: Print Sources Directory