trigger:
- dev


pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  displayName: 'Checkout dev branch'

- task: CmdLine@2
  inputs:
    script: |
      Write-Host "Build.SourcesDirectory: $env:Build_SourcesDirectory"
