trigger:
- dev

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  displayName: 'Checkout dev branch'

- task: CmdLine@2
  inputs:
    script: |
      sqlcmd -S <192.168.0.30> -d <neeraj> -U <User5> -P <CDev005#8> -i "$(Build.SourcesDirectory)\SQLQuery1.sql"
